services:
  postgres:
    image: postgres:16
    container_name: roombook-postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: roombook
      POSTGRES_USER: test
      POSTGRES_PASSWORD: ecminer
    volumes:
      - roombook_pg:/var/lib/postgresql/data

volumes:
  roombook_pg:
